# AI-NGFW Configuration
app:
  name: "AI-Driven Next-Generation Firewall"
  version: "1.0.0"
  description: "Advanced WAF with AI/ML-based threat detection and Zero Trust"

# Firewall Rules
firewall:
  default_action: "block"
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst: 20
  
  # Attack Detection Rules
  attack_signatures:
    sql_injection:
      enabled: true
      severity: "critical"
      patterns:
        - "(?i)(union|select|insert|update|delete|drop|create|alter).*?(from|into|table)"
        - "(?i)(or|and)\\s+['\"]?\\d+['\"]?\\s*=\\s*['\"]?\\d+['\"]?"
        - "(?i)(exec|execute|sp_|xp_)"
        - "(?i)(benchmark|sleep|waitfor)\\s*\\("
    
    xss:
      enabled: true
      severity: "high"
      patterns:
        - "(?i)<script[^>]*>.*?</script>"
        - "(?i)javascript:"
        - "(?i)on(load|error|click|mouse)\\s*="
        - "(?i)<iframe[^>]*>"
        - "(?i)eval\\s*\\("
    
    command_injection:
      enabled: true
      severity: "critical"
      patterns:
        - "(?i)[;&|]\\s*(cat|ls|wget|curl|nc|bash|sh|cmd)"
        - "(?i)\\$\\(.*?\\)"
        - "(?i)`.*?`"
    
    path_traversal:
      enabled: true
      severity: "high"
      patterns:
        - "\\.\\./|\\.\\.\\\\"
        - "(?i)%2e%2e[/\\\\]"
        - "(?i)(etc/passwd|win\\.ini)"
    
    ldap_injection:
      enabled: true
      severity: "medium"
      patterns:
        - "(?i)\\*\\)\\(.*?="
        - "(?i)\\)(\\||&)"
    
    xml_injection:
      enabled: true
      severity: "medium"
      patterns:
        - "(?i)<!DOCTYPE"
        - "(?i)<!ENTITY"
        - "(?i)<\\?xml"

# Machine Learning Models
ml_models:
  traffic_classifier:
    type: "cnn"
    architecture: "lightweight"
    input_size: 1500
    learning_rate: 0.001
    batch_size: 32
    epochs: 50
  
  anomaly_detector:
    algorithms:
      - name: "isolation_forest"
        contamination: 0.1
        n_estimators: 100
      - name: "dbscan"
        eps: 0.5
        min_samples: 5
      - name: "local_outlier_factor"
        n_neighbors: 20
  
  behavioral_analysis:
    type: "lstm"
    sequence_length: 10
    hidden_layers: [128, 64, 32]
  
  federated_learning:
    enabled: true
    aggregation_rounds: 10
    min_clients: 3
    privacy_budget: 1.0

# Zero Trust Architecture
zero_trust:
  authentication:
    methods:
      - "jwt"
      - "api_key"
      - "certificate"
    mfa_required: true
    biometric_enabled: false
  
  authorization:
    model: "rbac"  # Role-Based Access Control
    least_privilege: true
  
  micro_segmentation:
    enabled: true
    default_policy: "deny-all"
    segments:
      - name: "dmz"
        allowed_ips: ["0.0.0.0/0"]
      - name: "internal"
        allowed_ips: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
      - name: "sensitive"
        allowed_ips: ["10.0.1.0/24"]
  
  continuous_verification:
    enabled: true
    interval_seconds: 300
    risk_score_threshold: 70

# Threat Intelligence
threat_intelligence:
  feeds:
    - name: "abuse_ch"
      url: "https://urlhaus.abuse.ch/downloads/json/"
      type: "url"
      update_interval: 3600
    - name: "alienvault_otx"
      enabled: false  # Requires API key
      type: "ioc"
    - name: "mitre_attack"
      enabled: true
      url: "https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json"
      type: "ttps"
  
  stix_taxii:
    enabled: false  # Configure with your TAXII server
    server: "https://taxii.example.com"
    collection: "threat-intel"

# Automated Incident Response (SOAR)
soar:
  enabled: true
  workflows:
    - name: "block_malicious_ip"
      trigger: "high_severity_alert"
      actions:
        - type: "firewall_rule"
          action: "block_ip"
          duration: 3600
        - type: "notification"
          channels: ["email", "slack"]
    
    - name: "quarantine_suspicious_traffic"
      trigger: "anomaly_detected"
      actions:
        - type: "sandbox"
          action: "isolate"
        - type: "deep_inspection"
          enabled: true
    
    - name: "adaptive_rule_update"
      trigger: "zero_day_detected"
      actions:
        - type: "ml_model"
          action: "retrain"
        - type: "rule_generation"
          confidence_threshold: 0.9

# Performance & Monitoring
performance:
  max_throughput_gbps: 40
  target_latency_ms: 1
  max_concurrent_connections: 100000
  buffer_size: 65536
  
monitoring:
  metrics:
    - "requests_per_second"
    - "blocked_requests"
    - "latency_p50"
    - "latency_p95"
    - "latency_p99"
    - "cpu_usage"
    - "memory_usage"
    - "model_accuracy"
  
  alerts:
    - condition: "latency_p99 > 5"
      severity: "warning"
    - condition: "blocked_requests > 1000"
      severity: "critical"

# Compliance
compliance:
  frameworks:
    - "NIST_SP_800_207"
    - "ISO_27001"
    - "MITRE_ATTACK"
  
  audit_logging:
    enabled: true
    retention_days: 365
    encryption: true
